### ISSUE TITLE
small screens still scrunching

### ISSUE THREAD

**Issue by daveism** [nemac/ncdeq-viewer#137]
issues with padding between map and charts
issues with function categories to new line

**Comment by jdblack2** [comment]
I have not seen this since we last spoke.  On Friday we were seeing that to some extent b/c our projector changes the aspect ratio on our laptop screens by default when connected.

**Comment by daveism** [comment]
there is still some scrunching on small screens.  the main cause is there is too much padding between the maps and charts.  reducing the padding should allow the chart area to get a little more space and not cause issues

**Comment by daveism** [comment]
scrunching on mobile devices.
