### ISSUE TITLE
legends?

### ISSUE THREAD

**Issue by daveism** [nemac/ncdeq-viewer#143]

**Comment by jdblack2** [comment]
the need for a legend is eliminated if each of the TRA types is color coded much like the top categories in the bar charts

**Comment by daveism** [comment]
http://tiles.arcgis.com/tiles/PwLrOgCfU0cYShcG/arcgis/rest/services/Catchments/MapServer/legend?f=pjson

**Comment by daveism** [comment]
not needed...
